# Generated by Django 2.2.2 on 2020-07-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200731_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_saved_preferences',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
