# Generated by Django 2.2.2 on 2020-08-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_donation_subscription_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_membership_subscription_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
