# Generated by Django 2.2.2 on 2020-08-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userdonationsubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonationsubscriptions',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
