# Generated by Django 2.2.2 on 2020-08-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userdonationsubscriptions_is_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonationsubscriptions',
            name='date_terminated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
