# Generated by Django 2.2.2 on 2020-08-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userdonationsubscriptions_date_terminated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_donation_subscription_id',
        ),
    ]
