# Generated by Django 2.2.2 on 2020-08-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_userprofile_stripe_donation_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_membership_subscription_id',
        ),
    ]
