# Generated by Django 2.2.2 on 2020-08-02 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('M', 'Monthly'), ('O', 'One Time')], max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('monthly_price', models.IntegerField()),
                ('yearly_price', models.IntegerField()),
                ('stripe_monthly_price_id', models.CharField(max_length=50)),
                ('stripe_yearly_price_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MembershipType',
                'verbose_name_plural': 'MembershipTypes',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='MembershipDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_term', models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('date_joined', models.DateField()),
                ('date_terminated', models.DateField(blank=True, null=True)),
                ('is_paid_up', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.City')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.MembershipType')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Title')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MembershipDetail',
                'verbose_name_plural': 'MembershipDetails',
            },
        ),
        migrations.CreateModel(
            name='MemberPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MemberPaymentHistory',
                'verbose_name_plural': 'MemberPaymentHistories',
            },
        ),
    ]
