# Generated by Django 2.2.2 on 2020-08-03 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0002_auto_20200802_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='13@13.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_term',
            field=models.CharField(default='O', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_donation_subscription_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
