# Generated by Django 2.2.2 on 2020-08-03 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20200803_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='payment_term',
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
