# Generated by Django 2.2.2 on 2020-08-04 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20200803_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpaymenthistory',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
