# Generated by Django 2.2.2 on 2020-08-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_memberpaymenthistory_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='stripe_monthly_price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='stripe_yearly_price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
