# Generated by Django 2.2.2 on 2020-08-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20200811_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
