# Generated by Django 2.2.2 on 2020-08-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20200812_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipdetail',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.City'),
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Country'),
        ),
    ]
