# Generated by Django 2.2.2 on 2020-08-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20200812_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='yearly_price',
        ),
    ]
