# Generated by Django 2.2.2 on 2020-07-31 04:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20200727_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetail',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
            preserve_default=False,
        ),
    ]
