# Generated by Django 2.2.2 on 2020-08-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20200817_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
