# Generated by Django 2.2.2 on 2020-07-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_membershipdetail_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipdetail',
            old_name='city_id',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
