# Generated by Django 2.2.2 on 2020-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_donation_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
