# Generated by Django 2.2.2 on 2020-08-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_auto_20200731_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptype',
            old_name='membership_group',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='membershiptype',
            old_name='yearly_price_after_discount',
            new_name='yearly_price',
        ),
        migrations.RemoveField(
            model_name='membershipdetail',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='memberpaymenthistory',
            name='ref_code',
            field=models.CharField(default='123', max_length=25),
            preserve_default=False,
        ),
    ]
