# Generated by Django 2.2.2 on 2020-08-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_auto_20200819_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(choices=[('M', 'Monthly'), ('O', 'One Time')], max_length=50),
        ),
    ]
