# Generated by Django 2.2.2 on 2020-08-20 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_auto_20200820_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
