# Generated by Django 2.2.2 on 2020-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_donation_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
