# Generated by Django 2.2.2 on 2020-08-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_auto_20200820_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeDonationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_frequency', models.CharField(choices=[('M', 'Monthly'), ('O', 'One Time'), ('Y', 'Yearly')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(choices=[('M', 'Monthly'), ('O', 'One Time'), ('Y', 'Yearly')], max_length=50),
        ),
    ]
