# Generated by Django 2.2.2 on 2020-08-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_auto_20200822_0616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeDonationSubscription',
        ),
    ]
