# Generated by Django 2.2.2 on 2020-08-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_delete_stripedonationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_terminated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
