# Generated by Django 2.2.2 on 2020-08-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_donation_date_terminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(choices=[('M', 'Monthly'), ('O', 'One Time')], max_length=50),
        ),
    ]
