# Generated by Django 2.2.2 on 2020-08-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_auto_20200822_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetail',
            name='stripe_membership_subscription_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
